config/routes.rb
Rails.application.routes.draw do


  devise_for :users#, controllers: {registrations: "registrations"}

  # devise_scope :user do
  #   get "register", to: "devise/registrations#new"
  # end
  resources :wikis
  resources :subscribers
  get 'new_user_session' => 'devise/sessions#new'

  get 'new_user_password' => 'devise/password#new'
  get 'edit_user_password' => 'devise/passwords#edit'

  get 'cancel_user_registration' => 'registrations#cancel'
  get 'new_user_registration' => 'registrations#new'
  get 'edit_user_registration' => 'registrations#edit'
  get 'edit_user_registration' => 'registrations#edit'
  get 'register' => 'devise/registrations#new'

  get 'wikis' => 'wikis#index'
  get 'new_wiki' => 'wikis#new'
  get 'edit_wiki' => 'wikis#edit'
  get 'wiki' => 'wikis#show'

  get 'subscribers' => 'subscribers#index'
  get 'new_subscriber' => 'subscribers#new'
  get 'edit_subscriber' => 'subscribers#edit'
  get 'subscriber' => 'subscribers#show'

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :wikis
  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :standard }

  # validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :role,
             presence: true

  enum role: [:standard, :admin, :premium]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators

  default_scope { order('created_at DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

rescue_from Pundit::NotAuthorizedError do
  redirect_to root_url, alert: 'You do not have access to this page.'
end

  #private
  #def require_sign_in
  #  unless current_user
  #    flash[:alert] = "You must be logged in to do that"
  #    redirect_to new_session_path
  #  end
  #end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  #before_action :authenticate_user!

  def new

  end

  def create
    # Amount in cents
    @amount = 599


    # Create the customer in Stripe
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    # Create the charge using the customer data returned by Stripe API
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

    # place more code upon successfully creating the charge
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to subscribers_path
      flash[:notice] = "Please try again"
    end
  end
  #def update
  #  token = params[:stripeToken]

  #  customer = Stripe::Customer.create(
  #    card: token,
  #    plan: 1101,
  #    email: current_user.email,
  #  )

  #  current_user.subscribed = true
  #  current_user.stripeid = customer.id
  #  current_user.save

  #  redirect_to wikis_path
  #end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.role = params[:role]
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Blocipedia #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :authorize_user, except: [:show, :new, :create]
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  after_action :verify_authorized, except: :index
  #after_action :verify_policy_scoped, only: :index

  def index
    #@wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = current_user.wikis.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.create(wiki_params)
    #@wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def set_wiki
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body)
  end

  #def authorize_user
  #  wiki = Wiki.find(params[:id])
  #  unless current_user == @wiki.user || current_user.admin?
  #    flash[:alert] = "You must be an admin or a standard member to do that."
  #    redirect_to wiki
  #  end
#  end

## app/wikis/index.html.erb
#<%= @wikis.each do |wiki| %>
#  <%= link_to "#{wiki.title}", wiki %><br>
#  <% end %>

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  #def markdown(renderer)
  #  markdown = Redcarpet::Markdown.new(renderer)#.to_html.html_safe
  #end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wiki?
    current_user && (current_user == @wiki.user || current_user.admin?)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          <%= current_user.name %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Login', new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= value %>
        </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/subscribers/_form.html.erb
<!--
<%= form_tag subscriber_path(1), method: :put do %>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="A month's subscription"
        data-amount="599"></script><span> $5.99 per month, cancel at any time.</span>
<% end %>
-->

app/views/subscribers/create.html.erb
<h2>Thanks, you paid <strong>$5.99</strong>!</h2>

app/views/subscribers/new.html.erb
<!--
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
      <div class="panel-body">
        <%= render 'form' %>
    </div>
  </div>
</div>
-->
<!--
<div class="container">
<%= form_tag subscribers_path, id: 'stripeForm' do -%>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"></script>
  <article>
    <%= label_tag 'amount', 'Monthly Subscription', class: 'amount' %>
    <%= label_tag 'amount', "$5.99", class: "amount-figure" %>
  </article> <br>
  <button id="stripe-button">&nbsp;
  <%= label_tag 'title', 'Subscribe' %>
  <%= hidden_field_tag 'stripeToken' %>
  <%= hidden_field_tag 'stripeEmail' %>
  <%= hidden_field_tag 'stripeAmount' %>
  </button>
  <br><br>


  <script>
    var handler = StripeCheckout.configure({
      key: "<%= Stripe.api_key %>",
      token: function (token, args) {
        $("#stripeToken").value = token.id;
        $("#stripeAmount").value = <%= @amount %>;
        $("#stripeForm").submit();
      }
    });

    $('#stripe-button').on('click', function (e) {
      // Open Checkout with further options
        name: 'Your customer name',
        description: 'Monthly Subscription',
        amount: "$5.99"
      });
    e.preventDefault();
    });

    $(window).on('popstate', function() {
      handler.close();
    });
  </script>
</div>
<% end %>
-->
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<!--
<%= form_tag subscribers_path do %>
  <article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Amount: $5.99</span>
  </label>
  </article>
-->
  <form action="/subscribers/new" method="GET">
    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="pk_test_4WMQ6XpRHAjVqxOHS1GXopcZ"
      data-amount="599"
      data-name="ambercaldwell.net"
      data-description="Widget"
      data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
      data-locale="auto">
    </script>
  </form>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>
      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Sign up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Us</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vulputate magna leo, in accumsan ex congue vitae. Donec a turpis est. Suspendisse potenti. Cras ut ultrices sapien, a facilisis lectus. Nunc euismod malesuada ipsum, vitae semper nulla suscipit ac. Sed tempus lacus non lacus posuere, ut iaculis sem malesuada. Duis eget semper arcu, ac mattis enim. Curabitur consequat elementum velit, in molestie magna suscipit at. Vestibulum ut blandit lorem. Praesent nunc ligula, sollicitudin vel ligula in, elementum auctor magna. Vivamus pharetra risus eu viverra mollis. Morbi a malesuada mauris. Praesent non sollicitudin dui, auctor ultrices massa. Pellentesque neque lorem, dignissim quis porttitor vitae, imperdiet sit amet nisi.
<br><br>
Curabitur consequat ultricies vulputate. Aenean feugiat dolor eget eleifend maximus. Nunc vel magna a nulla facilisis pharetra id maximus ante. Duis eleifend, nunc eu porttitor tristique, mauris tellus egestas metus, non aliquam libero velit vitae augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras a nibh eu est laoreet tincidunt. In ut faucibus sem, sit amet convallis ante. Quisque sit amet convallis leo. Donec rhoncus ornare nibh, non pharetra odio efficitur eget.</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Blocipedia is a leading open-source resource containing information on most anything!</p>
  <p>
    <%= link_to 'Login', new_user_session_path %> or
    <%= link_to "Sign Up", new_user_registration_path %> today!
    <%= link_to "Become Premium", new_subscriber_path %>
  </p>
</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>
<%= form_for @wiki do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(wiki.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1><%= link_to "All Wikis", wikis_path %></h1>

<%= link_to "Create A Wiki", new_wiki_path %><br><br>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %> <br>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %>
  </small>
</h1>

<div class="row">
  <div class="col-md-8">
    <p><%= Redcarpet::Render::SmartyPants.render(@wiki.body) %></p>
  </div>
  <% if user_is_authorized_for_wiki? %>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki) if policy(@wiki).update? %>
    <%= link_to "Delete", wiki_path(@wiki), method: :delete if policy(@wiki).destroy? %>
  </div>
  <% end %>
</div>